// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkTc3zxAzAdTk8Auspa4bqRIRvovR1NBU',
    appId: '1:877611740911:android:fa4662021cc6d5f544f51a',
    messagingSenderId: '877611740911',
    projectId: 'emochat-skynet',
    storageBucket: 'emochat-skynet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBz58UkikdgBkj3yvF1jNBI4y0fb8nYf0',
    appId: '1:877611740911:ios:7e4289c2f1c802a144f51a',
    messagingSenderId: '877611740911',
    projectId: 'emochat-skynet',
    storageBucket: 'emochat-skynet.appspot.com',
    iosClientId: '877611740911-63anqifb4i8pvneoft6sr5sck77bjeku.apps.googleusercontent.com',
    iosBundleId: 'com.emochat.skynet',
  );
}
